### PR TITLE
Type header

### PR DESCRIPTION
**Pull request by Razzeee**
Also gets rid of menuCollapse which seemed unused?

### CODE REVIEW

**Comment by pkscout** [comment]
menuCollapse is the logic that builds the slightly smaller main menu for medium sized screens (i.e. most likely tablets).  Without it that screen size gets a mess of a menu.  Here's a screen shot of this PR without menuCollapse.  
Screen Shot 2021-03-26 at 3 27 10 PM

With menuCollapse a few of the menus would have gotten consolidated into a **More** menu.  I don't think there's a way for me to selectively accept parts of the PR, so you probably need to add that stuff back and check it with a smaller browser window (but not so small that the mobile menu becomes active).

**Comment by pkscout** [comment]
I guess alternatively we could make the mobile menu active on much larger screens, but I think there's a possibility that a 4:3 LCD display on a desktop might end up with the mobile menu.

**Review by pkscout — CHANGES_REQUESTED** [review]
see comments above

**Comment by Razzeee** [comment]
Revisited this

**Review by pkscout — APPROVED** [review]

**Pull request merged**
