### PR TITLE
Add Team Images

### PR DESCRIPTION
**Pull request by ampsteric**
This PR resolves the #188 issue.
Please review it and merge it.

Best regards.

### CODE REVIEW

**Comment by pkscout** [comment]
This page is managed in the Netlify CMS and should be edited there.  Any Kodi team member with access to the kodi-tv repo can login to the CMS to edit this page.  If you don't have access and need it, please request it in the Slack channel.  Please see the wiki on this repo for information on editing pages in the CMS.

**Comment by ampsteric** [comment]
@razzeee can you please at least review it as you had assigned me this issue to work on and I have already put 2 days of work to complete it.

**Comment by razzeee** [comment]
Yes, it does seem correct.

**Comment by ampsteric** [comment]
can you please merge it in that case and label it as "hacktoberfest-accepted"

**Comment by pkscout** [comment]
OK, I'm reopening this.  The deploy preview didn't work, which is often the case when you add new images this way.  This is why I don't like doing page edits outside the CMS, but I will merge it and hope for the best.

**Comment by ampsteric** [comment]
I do understand your point @pkscout , anyways thanks a lot for considering it.

**Comment by pkscout** [comment]
So, now the page is broken.  This is the last time I merge a CMS page this way.

**Comment by pkscout** [comment]
Fixed now.

**Pull request merged**
