### PR TITLE
Add filters to sponsors

### PR DESCRIPTION
**Pull request by Razzeee**
Can't get this to work. Maybe you can @pkscout I think the css isn't created correctly.
Filters are a new feature (so it might actually be broken?) https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.1.0

### CODE REVIEW

**Comment by pkscout** [comment]
The site is using the JIT compiler for CSS, so maybe that needs to be updated as well?

`"@tailwindcss/jit": "^0.1.18",`

To test that, you can change the postcss.config file to use the "standard" tailwindcss by changing the line that says `"@tailwindcss/jit": {},` to `"@tailwindcss": {},`

**Comment by Razzeee** [comment]
Will try later. I actually tried to switch to the now included jit, but that basically broke everything.

**Comment by Razzeee** [comment]
Working now, but not sure why `global.css` explodes like that.

**Review by pkscout — APPROVED** [review]

**Comment by pkscout** [comment]
The global.css in static/admin is so that the live previews in the CMS look like the site. It has to be a static sheet and include all of the Tailwind stuff, so if Tailwind added some new features I'm not surprised that the class list exploded like that. The good news is that file is only used by the CMS, so it won't affect general load times any.

**Pull request merged**
