### PR TITLE
Update Distribution “windows-21a1”

### PR DESCRIPTION
**Pull request by KarellenX**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by KarellenX** [comment]
@pkscout 

I manually changed the title to **21-a1** from the default "windows-19".

How can I force these automatically generated PR's to use the version number that matches the version number that I am updating?

ie windows-20, windows-21 etc

**Comment by pkscout** [comment]
I don't know off hand.  I think when I originally set all this up there was a reason for the numbering in that name, but it was never needed, and I don't think you ever see it except for the Github stuff.

**Comment by KarellenX** [comment]
Ok, thanks. I was looking for the wording for the pre-release tab, so it took a while to narrow down to it. So wondered if it was possible to change the title to match and make it easier in future.

No biggie. Just thought if it was easy to change I would do so.

**Comment by razzeee** [comment]
The titles don't have any significance, they only help you finding things. I will remove the numbers from the file names.

**Pull request merged**
