### PR TITLE
Key all mapped iterations

### PR DESCRIPTION
**Pull request by Razzeee**
Rename HeaderDropdownMenu so that it maches it's Component name

### CODE REVIEW

**Review by pkscout — APPROVED** [review]
Is the convention in React to use relative paths? I literally just made sure everything was using absolute paths (src is mapped by a Gatsby plugin) so that if we ever move things around we don't have to fix all the relative paths. But if relative pathing is the convention, I'll live with it.

**Comment by Razzeee** [comment]
Vscode at least complains about these. Then again, I think in mdx files it's still a problem?

**Comment by pkscout** [comment]
OK.  I'll fix them today.  I think their mostly in src/templates and src/components anyway, and those are stable. By the time I'm done, we may not have any MDX files anyway. Those I would like to leave as src/components as long as VSCode only complains when you open a file. It makes it easier if you copy one to start another in a different location.

**Comment by Razzeee** [comment]
Yeah, I don't think it cares for those at all, will check later. 

I might want to cluster some of the components into folders at some point :)

**Pull request merged**
